### PR TITLE
Fix docker registry reboot

### PR DESCRIPTION
**Pull request by rewiko**
Reboot is failing when you have more than 1 pod into the same namespace.

### CODE REVIEW

**Review by sebbonnet — COMMENTED** [review]
Why don't we have static script file instead of generating a script that we then execute? I think it would be much easier to read

**Comment by jsravn** [comment]
Agree w/ @sebbonnet. To handle the env vars, you could create a much simpler file dynamically and source that instead. Leaving the more complicated logic to a dedicated/static file.

**Comment by rewiko** [comment]
ready to review

**Review by sebbonnet — COMMENTED** [review]
Looks better.

Any reason to use `/var/log/clean-images-registry.log` other than to keep the container running?
Wouldn't it better to let everything go to stdout and change the /sbin/my_init command to tail -f /dev/null - this would make the intent clearer.

We could also setup the cron job statically in the docker image and invoke the /sbin/my_init command directly as the entrypoint.
 
WDYT?

**Comment by rewiko** [comment]
> We could also setup the cron job statically in the docker image and invoke the /sbin/my_init
> command directly as the entrypoint.

If we do that, we will lose the avantage to customize the schedule time of the cron at runtime.

> Any reason to use /var/log/clean-images-registry.log other than to keep the container running?

It's not to keep running the container, that's just to print the output, if we can print everything to stdout, would be better.

**Comment by rewiko** [comment]
we can redirect output to `/dev/stdout`, but the script exec another so we won't  have the full log.

**Review by sebbonnet — APPROVED** [review]

**Pull request merged**
